#!/bin/csh -f

# This makes a MacOS X package starting with stand-alone Wish.app.

set V = 8_2
set DV = 4_1_4

if ( -f $HOME/tkcvs_$V ) rm -rf $HOME/tkcvs_$V
mkdir $HOME/tkcvs_$V
set Target = $HOME/tkcvs_$V/TkCVS.app
echo "Ditto Target"
ditto $HOME/Downloads/Wish\ Shell.app $Target
#ditto $HOME/Downloads/Wish8.4.10.app $Target
chmod -R +w $Target/*

echo "Installing Icons"
cp tkcvs/bitmaps/Anglerfish.icns $Target/Contents/Resources
chmod 644 $Target/Contents/Resources/Anglerfish.icns
cp Info.plist $Target/Contents

echo "Making Lib Directories"
rm -rf    $Target/Contents/Resources/Scripts
mkdir     $Target/Contents/Resources/Scripts
mkdir     $Target/Contents/Resources/Scripts/bin
mkdir     $Target/Contents/Resources/Scripts/lib
mkdir     $Target/Contents/Resources/Scripts/lib/tkcvs
mkdir     $Target/Contents/Resources/Scripts/lib/tkcvs/bitmaps

echo "Installing Scripts"
echo "source [file join [file dirname [info script]] bin/tkcvs.tcl]" > \
        $Target/Contents/Resources/Scripts/AppMain.tcl
cp tkcvs/tkcvs.tcl $Target/Contents/Resources/Scripts/bin/tkcvs.tcl
chmod +x  $Target/Contents/Resources/Scripts/bin/tkcvs.tcl
cp tkcvs/*.tcl $Target/Contents/Resources/Scripts/lib/tkcvs
cp tkcvs/tclIndex $Target/Contents/Resources/Scripts/lib/tkcvs
rm $Target/Contents/Resources/Scripts/lib/tkcvs/tkcvs.tcl
cp tkcvs/bitmaps/*.{gif,xbm} $Target/Contents/Resources/Scripts/lib/tkcvs/bitmaps

cp COPYING FAQ INSTALL $HOME/tkcvs_$V
cp CHANGELOG $HOME/tkcvs_$V

# Make sure TkDiff is ready
cp -r $HOME/tkdiff-$DV-macos/TkDiff.app $HOME/tkcvs_$V

cd $HOME

echo "Creating DMG...  This uses sudo, which prompts for a password."
if ( -f "tkcvs_$V.dmg" ) rm -f "tkcvs_$V.dmg"
sudo bin/buildDMG.pl -debug -dmgName tkcvs_$V -volName TkCVS_$V tkcvs_$V/*

echo "Compressing DMG."
if ( -f "tkcvs_$V.dmg.gz" ) rm -f "tkcvs_$V.dmg.gz"
gzip tkcvs_$V.dmg

echo "Created:"
ls -al tkcvs_$V.dmg.gz

# This is the way it will be invoked on a double-click, so it had
# better be able to handle it
echo "See if it works"
echo "$Target/Contents/MacOS/Wish Shell -psn_0_7995393"
"$Target/Contents/MacOS/Wish Shell" -psn_0_7995393
#$Target/Contents/MacOS/Wish -psn_0_7995393

 
