# Keep all the images in one place
proc load_all_images {} {
  global cvscfg
  
  # App icon
  image create photo AppIcon64 -format gif -file [file join $cvscfg(bitmapdir) Toothyfish_128.gif]
  image create photo Blame -format gif -file [file join $cvscfg(bitmapdir) wm_blame.gif]
  image create photo Branch -format gif -file [file join $cvscfg(bitmapdir) wm_branch.gif]
  image create photo Merge -format gif -file [file join $cvscfg(bitmapdir) wm_merge.gif]
  image create photo Help -format gif -file [file join $cvscfg(bitmapdir) wm_help.gif]
  image create photo Says -format gif -file [file join $cvscfg(bitmapdir) wm_says.gif]
  image create photo Trace -format gif -file [file join $cvscfg(bitmapdir) wm_trace.gif]
  
  # Buttons
  image create photo Add -format gif -file [file join $cvscfg(bitmapdir) add.gif]
  image create photo Annotate -format gif -file [file join $cvscfg(bitmapdir) annotate.gif]
  image create photo Branches -format gif -file [file join $cvscfg(bitmapdir) branch.gif]
  image create photo BranchNo -format gif -file [file join $cvscfg(bitmapdir) lightning.gif]
  image create photo Branchtag -format gif -file [file join $cvscfg(bitmapdir) branchtag.gif]
  image create photo Check -format gif -file [file join $cvscfg(bitmapdir) check.gif]
  image create photo Checkin -format gif -file [file join $cvscfg(bitmapdir) checkin.gif]
  image create photo Checkout -format gif -file [file join $cvscfg(bitmapdir) checkout.gif]
  image create photo CheckoutOpts -format gif -file [file join $cvscfg(bitmapdir) checkout_opts.gif]
  image create photo Conflict -format gif -file [file join $cvscfg(bitmapdir) conflict.gif]
  image create photo Delete -format gif -file [file join $cvscfg(bitmapdir) delete.gif]
  image create photo Diff -format gif -file [file join $cvscfg(bitmapdir) delta_feather.gif]
  image create photo Difflines -format gif -file [file join $cvscfg(bitmapdir) difflines.gif]
  image create photo DirBranches -format gif -file [file join $cvscfg(bitmapdir) dirbranch.gif]
  image create photo Dir_new -format gif -file [file join $cvscfg(bitmapdir) folder_new.gif]
  image create photo Edit -format gif -file [file join $cvscfg(bitmapdir) edit.gif]
  image create photo Export -format gif -file [file join $cvscfg(bitmapdir) export.gif]
  image create photo Fileedit -format gif -file [file join $cvscfg(bitmapdir) fileedit.gif]
  image create photo Files -format gif -file [file join $cvscfg(bitmapdir) files.gif]
  image create photo Fileview -format gif -file [file join $cvscfg(bitmapdir) fileview.gif]
  image create photo Folder -format gif -file [file join $cvscfg(bitmapdir) dir.gif]
  image create photo GitCheckin -format gif -file [file join $cvscfg(bitmapdir) git_checkin.gif]
  image create photo GitCheckout -format gif -file [file join $cvscfg(bitmapdir) git_checkout.gif]
  image create photo Import -format gif -file [file join $cvscfg(bitmapdir) import.gif]
  image create photo Lock -format gif -file [file join $cvscfg(bitmapdir) locked.gif]
  image create photo Log -format gif -file [file join $cvscfg(bitmapdir) log.gif]
  image create photo Man -format gif -file [file join $cvscfg(bitmapdir) man.gif]
  image create photo Mergebranch -format gif -file [file join $cvscfg(bitmapdir) newmerge_simple.gif]
  image create photo Mergebranch -format gif -file [file join $cvscfg(bitmapdir) newmerge_simple.gif]
  image create photo Mergediff -format gif -file [file join $cvscfg(bitmapdir) newmerge.gif]
  image create photo Mergediff -format gif -file [file join $cvscfg(bitmapdir) newmerge.gif]
  image create photo Modules -format gif -file [file join $cvscfg(bitmapdir) modbrowse.gif]
  image create photo Modules_cvs -format gif -file [file join $cvscfg(bitmapdir) modbrowse_cvs.gif]
  image create photo Modules_git -format gif -file [file join $cvscfg(bitmapdir) modbrowse_git.gif]
  image create photo Modules_svn -format gif -file [file join $cvscfg(bitmapdir) modbrowse_svn.gif]
  image create photo Patches -format gif -file [file join $cvscfg(bitmapdir) rdiff.gif]
  image create photo Patchfile -format gif -file [file join $cvscfg(bitmapdir) patchfile.gif]
  image create photo Refresh -format gif -file [file join $cvscfg(bitmapdir) loop-glasses.gif]
  image create photo Remove -format gif -file [file join $cvscfg(bitmapdir) remove.gif]
  image create photo Revert -format gif -file [file join $cvscfg(bitmapdir) loop-ball.gif]
  image create photo SvnRemove -format gif -file [file join $cvscfg(bitmapdir) delete_red.gif]
  image create photo Tag -format gif -file [file join $cvscfg(bitmapdir) tag.gif]
  image create photo Tags -format gif -file [file join $cvscfg(bitmapdir) tags.gif]
  image create photo UnLock -format gif -file [file join $cvscfg(bitmapdir) unlocked.gif]
  image create photo Unedit -format gif -file [file join $cvscfg(bitmapdir) unedit.gif]
  image create photo Who -format gif -file [file join $cvscfg(bitmapdir) who.gif]
  image create photo Workdir -format gif -file [file join $cvscfg(bitmapdir) folderopen.gif]
  image create photo arr_dn -format gif -file [file join $cvscfg(bitmapdir) arrow_dn.gif]
  image create photo arr_up -format gif -file [file join $cvscfg(bitmapdir) arrow_up.gif]
  image create photo updir -format gif -file [file join $cvscfg(bitmapdir) updir.gif]
  
  # CVS module icons for treeview
  image create photo adir -format gif -file [file join $cvscfg(bitmapdir) adir.gif]
  image create photo amod -format gif -file [file join $cvscfg(bitmapdir) amod.gif]
  image create photo dir -format gif -file [file join $cvscfg(bitmapdir) dir.gif]
  image create photo mdir -format gif -file [file join $cvscfg(bitmapdir) mdir.gif]
  image create photo mod -format gif -file [file join $cvscfg(bitmapdir) mod.gif]
  
  # Files and folders
  image create photo cvsdir -format gif -file [file join $cvscfg(bitmapdir) dir_cvs.gif]
  image create photo dir_minus -format gif -file [file join $cvscfg(bitmapdir) dir_minus.gif]
  image create photo dir_mod -format gif -file [file join $cvscfg(bitmapdir) dir_mod.gif]
  image create photo dir_ok -format gif -file [file join $cvscfg(bitmapdir) dir_ok.gif]
  image create photo dir_ood -format gif -file [file join $cvscfg(bitmapdir) dir_ood.gif]
  image create photo dir_plus -format gif -file [file join $cvscfg(bitmapdir) dir_plus.gif]
  image create photo dir -format gif -file [file join $cvscfg(bitmapdir) dir.gif]
  image create photo gitdir -format gif -file [file join $cvscfg(bitmapdir) dir_git.gif]
  image create photo link -format gif -file [file join $cvscfg(bitmapdir) link.gif]
  image create photo link_mod -format gif -file [file join $cvscfg(bitmapdir) link_mod.gif]
  image create photo link_modml -format gif -file [file join $cvscfg(bitmapdir) link_modml.gif]
  image create photo link_modol -format gif -file [file join $cvscfg(bitmapdir) link_modol.gif]
  image create photo link_ok -format gif -file [file join $cvscfg(bitmapdir) link_ok.gif]
  image create photo link_okml -format gif -file [file join $cvscfg(bitmapdir) link_okml.gif]
  image create photo link_okol -format gif -file [file join $cvscfg(bitmapdir) link_okol.gif]
  image create photo link_plus -format gif -file [file join $cvscfg(bitmapdir) link_plus.gif]
  image create photo paper -format gif -file [file join $cvscfg(bitmapdir) paper.gif]
  image create photo rcsdir -format gif -file [file join $cvscfg(bitmapdir) dir_rcs.gif]
  image create photo stat_conf -format gif -file [file join $cvscfg(bitmapdir) stat_conf.gif]
  image create photo stat_cvsplus_kb -format gif -file [file join $cvscfg(bitmapdir) stat_plus_kb.gif]
  image create photo stat_ex -format gif -file [file join $cvscfg(bitmapdir) stat_ex.gif]
  image create photo stat_kb -format gif -file [file join $cvscfg(bitmapdir) stat_kb.gif]
  image create photo stat_merge -format gif -file [file join $cvscfg(bitmapdir) stat_merge.gif]
  image create photo stat_minus -format gif -file [file join $cvscfg(bitmapdir) stat_minus.gif]
  image create photo stat_mod -format gif -file [file join $cvscfg(bitmapdir) stat_mod.gif]
  image create photo stat_mod_green -format gif -file [file join $cvscfg(bitmapdir) stat_mod_green.gif]
  image create photo stat_mod_red -format gif -file [file join $cvscfg(bitmapdir) stat_mod_red.gif]
  image create photo stat_modml -format gif -file [file join $cvscfg(bitmapdir) stat_modml.gif]
  image create photo stat_modol -format gif -file [file join $cvscfg(bitmapdir) stat_modol.gif]
  image create photo stat_ok -format gif -file [file join $cvscfg(bitmapdir) stat_ok.gif]
  image create photo stat_okml -format gif -file [file join $cvscfg(bitmapdir) stat_okml.gif]
  image create photo stat_okol -format gif -file [file join $cvscfg(bitmapdir) stat_okol.gif]
  image create photo stat_ood -format gif -file [file join $cvscfg(bitmapdir) stat_ood.gif]
  image create photo stat_oodml -format gif -file [file join $cvscfg(bitmapdir) stat_oodml.gif]
  image create photo stat_plus -format gif -file [file join $cvscfg(bitmapdir) stat_plus.gif]
  image create photo stat_ques -format gif -file [file join $cvscfg(bitmapdir) stat_ques.gif]
  image create photo svndir -format gif -file [file join $cvscfg(bitmapdir) dir_svn.gif]
}

