#!/bin/csh -f

# This makes a MacOS X package starting with stand-alone Wish.app.

set V = 8_2_1
set DV = 4_1_4

#set TkV = 8.4.8
set TkV = 8.4.19
#set TkV = 8.5.8
#set TkV = 8.6b1
set WISH_SH = "Wish$TkV"
set WISH_APP = "$HOME/Downloads/$WISH_SH.app"

set TKCVS_Target = tkcvs_${V}_$TkV

if ( -f $HOME/$TKCVS_Target ) rm -rf $HOME/$TKCVS_Target
mkdir $HOME/$TKCVS_Target
set Target = $HOME/$TKCVS_Target/TkCVS.app
echo "Ditto Target"
ditto $WISH_APP $Target
chmod -R +w $Target/*

echo "Installing Icons"
cp tkcvs/bitmaps/Anglerfish.icns $Target/Contents/Resources
chmod 644 $Target/Contents/Resources/Anglerfish.icns
cp Info.plist $Target/Contents

echo "Making Lib Directories"
rm -rf    $Target/Contents/Resources/Scripts
mkdir     $Target/Contents/Resources/Scripts
mkdir     $Target/Contents/Resources/Scripts/bin
mkdir     $Target/Contents/Resources/Scripts/lib
mkdir     $Target/Contents/Resources/Scripts/lib/tkcvs
mkdir     $Target/Contents/Resources/Scripts/lib/tkcvs/bitmaps

echo "Installing Scripts"
echo "source [file join [file dirname [info script]] bin/tkcvs.tcl]" > \
        $Target/Contents/Resources/Scripts/AppMain.tcl
cp tkcvs/tkcvs.tcl $Target/Contents/Resources/Scripts/bin/tkcvs.tcl
chmod +x  $Target/Contents/Resources/Scripts/bin/tkcvs.tcl
cp tkcvs/*.tcl $Target/Contents/Resources/Scripts/lib/tkcvs
cp tkcvs/tclIndex $Target/Contents/Resources/Scripts/lib/tkcvs
rm $Target/Contents/Resources/Scripts/lib/tkcvs/tkcvs.tcl
cp tkcvs/bitmaps/*.{gif,xbm} $Target/Contents/Resources/Scripts/lib/tkcvs/bitmaps

cp COPYING FAQ INSTALL $HOME/$TKCVS_Target
cp CHANGELOG $HOME/$TKCVS_Target

# Make sure TkDiff is ready
cp -r $HOME/tkdiff-$DV-macos/TkDiff.app $HOME/$TKCVS_Target

cd $HOME

echo "Creating DMG"
if ( -f "tkcvs_$V.dmg" ) rm -f "tkcvs_$V.dmg"
echo "hdiutil create -fs HFS+ -volname TkCVS_$V -srcfolder tkcvs_${V}_$TkV tkcvs_$V.dmg"
hdiutil create -fs "HFS+" -volname TkCVS_$V -srcfolder tkcvs_${V}_$TkV tkcvs_$V.dmg
if ($status != 0) exit

echo "Compressing DMG."
if ( -f "tkcvs_$V.dmg.gz" ) rm -f "tkcvs_$V.dmg.gz"
gzip tkcvs_$V.dmg

echo "Created:"
ls -al tkcvs_$V.dmg.gz

# This is the way it will be invoked on a double-click, so it had
# better be able to handle it
echo "See if it works"
echo "$Target/Contents/MacOS/Wish -psn_0_7995393"
"$Target/Contents/MacOS/Wish" -psn_0_7995393
 
