#!/bin/sh
#-*-tcl-*-
# the next line restarts using tclsh \
exec tclsh "$0" -- ${1+"$@"}

puts "making tclIndex"

auto_mkindex . \
  annotate.tcl \
  branch_diagram.tcl \
  style_params.tcl \
  cvs.tcl \
  dialog.tcl \
  diff.tcl \
  dircanvas.tcl \
  errors.tcl \
  exec.tcl \
  filebrowse.tcl \
  gen_log.tcl \
  git.tcl \
  help.tcl \
  import.tcl \
  import2.tcl \
  joincanvas.tcl \
  load_images.tcl \
  menubar.tcl \
  modbrowse.tcl \
  modules.tcl \
  preferences.tcl \
  rcs.tcl \
  ui_misc.tcl \
  static.tcl \
  svn-import.tcl \
  svn.tcl \
  tkcvs.tcl \
  tkcvs_def.tcl \
  tooltips.tcl \
  vendor_merge.tcl \
  workdir.tcl

puts "done"
exit
