#!/bin/sh

# Make some directories with unique files in them.
WORDLIST="fortune initstate quiz rand red"

rm -rf Dir* File*
for n in 1 2 3
do
  # Random word
  R=`echo $WORDLIST | gawk '{print $((systime()%NF)+1)}'`
  echo "File$n"
  echo $R > "File$n"
done

for D in Dir1 "Dir 2"
do
  echo $D
  mkdir "$D"
  for n in 1 2
  do
    echo "  $D/F$n"
    R=`echo $WORDLIST | gawk '{print $((systime()%NF)+1)}'`
    echo $R > "$D/F$n"
  done
  echo "  $D/F 4"
  echo $R > "$D/F 4"
done
