#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" -- ${1+"$@"}

set WD [pwd]
set Root [file join $WD "CVS_REPOSITORY"]

if {[ file isdirectory $Root ]} {
  file delete -force $Root
}
set oldirs [glob -nocomplain -- cvs_test*]
foreach od $oldirs {
  puts "Deleting $od"
  file delete -force $od
}

