#!/bin/sh

WORDLIST="barcode braid greynetic maze mountain pacman triangle vidwhacker wander"
R=`echo $WORDLIST | gawk '{print $((systime()%NF)+1)}'`

# Finally found something that will work on the PC
find . -name .svn -prune -o -name CVS -prune -o -type f -print > FILES-modtest-tmp
echo "****************************"
sed '/FILES-modtest-tmp$/d' FILES-modtest-tmp > FILES-modtest-tmp1
gawk '/..*/ {print "echo \"'$R'\" >> \"" $0 "\""}' FILES-modtest-tmp1 > FILES-modtest-tmp
cat FILES-modtest-tmp
sh FILES-modtest-tmp
rm FILES-modtest-tmp  FILES-modtest-tmp1
